version: '3.1'

services:

  db:
    image: postgres
    env_file:
      - ./django-polls.env

  app-server:
    depends_on:
      - db
    image: krisocc/app-server:1.0
    command: bash run-server.sh
    env_file:
      - ./django-polls.env
    ports:
      - 8000:8000
